/* This file was automatically generated by µCurve (ucurve).
 * DO NOT EDIT MANUALLY, WILL BE OVERWRITTEN.
 * Creation: 2018-01-11 20:18:39
 */

#ifndef __NTC_ADU2DEGC_H__
#define __NTC_ADU2DEGC_H__

#include <stdint.h>

int16_t ntc_adu2degc(uint8_t value);

#endif
